Update english-spanish-Part 2-Family 2.csv
jmbeach/duolingo-vocab-lists pull request #9
Opened 2022-09-13 01:12 UTC by lazaridoue

2022-09-13 13:45 UTC, jmbeach requested changes

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +italiano,Italian (m)
I like adding the m

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +italiana, Italian (f)
I don't want to necessarily add every gender of adjective unless it's a special case

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +su,his/her
good change

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +hija,daughter
this one is in Part1 family and I wanted to avoid duplicates throughout the whole program

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +pequeña, small (f)
same thing, want to avoid adding every gender unless it's hard to guess

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +simpático,nice (m)
same thing

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +alta,tall (f)
same thing

2022-09-13 13:45 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +baja,short (f)
same thing

2022-09-21 00:44 UTC, lazaridoue commented
Recommitted with the changes

2022-09-21 12:49 UTC, jmbeach commented on english-spanish/Part 2/english-spanish-Part 2-Family 2.csv
> +simpático,nice (m)
I appreciate your work on this! would you mind changing this back to feminine so that there's still a good mix of seeing adjectives as either gender?

2022-10-16 17:21 UTC, jmbeach approved these changes

2022-10-16 17:21 UTC, merged